CREATE FUNCTION FUNCTION_CUSTOMER_ID(@CUSTOMER_NAME VARCHAR(MAX))
RETURNS INT
AS
BEGIN
	DECLARE @ret INT
	SET @ret = (SELECT ID FROM CUSTOMER WHERE USERNAME = @CUSTOMER_NAME)
	IF (@ret IS NULL)
		SET @ret = 0;
	RETURN @ret;
END;
GO

CREATE FUNCTION FUNCTION_CONSOLE_ID(@CONSOLE_NAME VARCHAR(MAX))
RETURNS INT
AS
BEGIN
	DECLARE @ret INT
	SET @ret = (SELECT ID FROM CONSOLE WHERE CONSOLENAME = @CONSOLE_NAME)
	IF (@ret IS NULL)
		SET @ret = 0;
	RETURN @ret;
END;
GO

CREATE FUNCTION FUNCTION_GAME_ID(@GAME_NAME VARCHAR(MAX))
RETURNS INT
AS
BEGIN
	DECLARE @ret INT
	SET @ret = (SELECT ID FROM GAME WHERE GAMENAME = @GAME_NAME)
	IF (@ret IS NULL)
		SET @ret = 0;
	RETURN @ret;
END;
GO

CREATE FUNCTION FUNCTION_ACCESSORY_ID(@ACCESSORY_NAME VARCHAR(MAX))
RETURNS INT
AS
BEGIN
	DECLARE @ret INT
	SET @ret = (SELECT ID FROM ACCESSORY WHERE ACCESSNAME = @ACCESSORY_NAME)
	IF (@ret IS NULL)
		SET @ret = 0;
	RETURN @ret;
END;
GO