CREATE TABLE CUSTOMER (
	ID INT NOT NULL UNIQUE IDENTITY(1,1),
	USERNAME CHAR(50) NOT NULL,
	RHOURS INT NOT NULL,
	RMINS INT NOT NULL,
	RSECS INT NOT NULL,
		CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY(ID)
);

CREATE TABLE CONSOLE (
	ID INT NOT NULL UNIQUE IDENTITY(1,1),
	CUSTOMER_ID INT NOT NULL,
	CONSOLENAME VARCHAR(20) NOT NULL,
		CONSTRAINT PK_CONSOLE_ID PRIMARY KEY(ID),
		CONSTRAINT FK_CONSOLE_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE GAME (
	ID INT NOT NULL UNIQUE IDENTITY(1,1),
	CONSOLE_ID INT NOT NULL,
	GAMENAME VARCHAR(50) NOT NULL,
		CONSTRAINT PK_GAME_ID PRIMARY KEY (ID),
		CONSTRAINT FK_GAME_CONSOLE_ID FOREIGN KEY (CONSOLE_ID) REFERENCES CONSOLE(ID)
);

CREATE TABLE ACCESSORY (
	ID INT NOT NULL UNIQUE IDENTITY(1,1),
	CONSOLE_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	ACCESSNAME VARCHAR(50) NOT NULL,
		CONSTRAINT PK_ACCESSORY_ID PRIMARY KEY (ID),
		CONSTRAINT FK_ACCESSORY_CONSOLE_ID FOREIGN KEY (CONSOLE_ID) REFERENCES CONSOLE(ID),
		CONSTRAINT FK_ACCESSORY_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);


