INSERT INTO CUSTOMER(USERNAME, RHOURS, RMINS, RSECS) VALUES ('CALEJAND', 12, 15, 07);
INSERT INTO CUSTOMER(USERNAME, RHOURS, RMINS, RSECS) VALUES ('JSALOMA', 8, 17, 05);
INSERT INTO CUSTOMER(USERNAME, RHOURS, RMINS, RSECS) VALUES ('SHARDING', 24, 10, 05);
